name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./config/server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Roberto
      - APELLIDO=Ramirez
      - DOCUMENTO=40566677
      - NACIMIENTO=1947-09-29
      - NUMERO=6000
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./config/client/config.yaml:/config.yaml

  netcat:
    container_name: netcat
    image: alpine:latest
    entrypoint: [ "/bin/sh", "./validar-echo-server.sh" ]
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./validar-echo-server.sh:/validar-echo-server.sh

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
